console.log('Addition');
var xAdd = 5;
xAdd += 10;
console.log(xAdd);
console.log('Subtraction');
var xSub = 10;
xSub -= 5;
console.log(xSub);
console.log('Multiplication');
var xMul = 5;
xMul *= 5;
console.log(xMul);
console.log('Division');
var xDiv = 6;
xDiv /= 3;
console.log(xDiv);
