console.log('Addition');
let xAdd:number = 5;
xAdd += 10;
console.log(xAdd);
console.log('Subtraction');
let xSub:number = 10;
xSub -= 5;
console.log(xSub);
console.log('Multiplication');
let xMul:number = 5;
xMul *=5;
console.log(xMul);
console.log('Division');
let xDiv:number = 6;
xDiv /= 3;
console.log(xDiv);